/**
 * EpisodeTrajectory -- Forecast-based trajectory visualization.
 *
 * Shows near-term and medium-term trajectory directions,
 * recovery indications, and forecast reliability labels.
 *
 * Uses existing HORIZON_META for reliability labels.
 * No numeric confidence scores generated by this component.
 */

import { HORIZON_META } from '../../constants';

/**
 * Arrow indicator for trajectory direction.
 */
function TrajectoryArrow({ direction }) {
  const arrows = {
    rising: { symbol: '\u2197', color: '#dc2626', label: 'Rising' },
    stable: { symbol: '\u2192', color: '#a16207', label: 'Stable' },
    falling: { symbol: '\u2198', color: '#16a34a', label: 'Falling' },
    unknown: { symbol: '\u2014', color: '#64748b', label: 'Unknown' },
  };
  const a = arrows[direction] || arrows.unknown;

  return (
    <span
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: '6px',
        fontSize: '14px',
        fontWeight: 600,
        color: a.color,
      }}
      title={a.label}
    >
      <span style={{ fontSize: '18px' }}>{a.symbol}</span>
      <span>{a.label}</span>
    </span>
  );
}

/**
 * Forecast reliability badge using existing HORIZON_META.
 */
function ReliabilityBadge({ horizon, reliabilityMap }) {
  const label = reliabilityMap?.[`${horizon}h`];
  if (!label) return null;

  const meta = HORIZON_META[horizon];
  const confidence = meta?.confidence || 'moderate';

  const colors = {
    high: { bg: '#f0fdf4', text: '#166534', border: '#bbf7d0' },
    moderate: { bg: '#fefce8', text: '#854d0e', border: '#fde68a' },
    lower: { bg: '#fef2f2', text: '#991b1b', border: '#fecaca' },
  };
  const c = colors[confidence] || colors.moderate;

  return (
    <span style={{
      fontSize: '11px',
      fontWeight: 500,
      color: c.text,
      background: c.bg,
      border: `1px solid ${c.border}`,
      padding: '2px 6px',
      borderRadius: 4,
    }}>
      {label}
    </span>
  );
}

/**
 * Main EpisodeTrajectory component.
 */
export default function EpisodeTrajectory({ episode }) {
  if (!episode) return null;

  const {
    near_term,
    medium_term,
    recovery_expected,
    recovery_text,
    highest_forecast_horizon,
    highest_forecast_value,
    peak_passed,
    trajectory_description,
    forecast_reliability,
  } = episode;

  return (
    <div style={{
      border: '1px solid var(--slate-200)',
      borderRadius: 'var(--radius)',
      overflow: 'hidden',
    }}>
      {/* Header */}
      <div style={{
        padding: 'var(--sp-3) var(--sp-4)',
        background: 'var(--slate-50)',
        borderBottom: '1px solid var(--slate-200)',
        fontSize: 'var(--text-sm)',
        fontWeight: 600,
        color: 'var(--slate-800)',
      }}>
        Trajectory
      </div>

      <div style={{ padding: 'var(--sp-4)' }}>
        {/* Trajectory description */}
        {trajectory_description && (
          <div style={{
            fontSize: '14px',
            color: 'var(--slate-700)',
            marginBottom: 'var(--sp-3)',
          }}>
            {trajectory_description}
          </div>
        )}

        {/* Direction indicators */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: '1fr 1fr',
          gap: 'var(--sp-3)',
          marginBottom: 'var(--sp-3)',
        }}>
          <div style={{
            padding: 'var(--sp-3)',
            background: 'var(--slate-50)',
            borderRadius: '6px',
          }}>
            <div style={{
              fontSize: '12px',
              color: 'var(--slate-500)',
              marginBottom: '4px',
            }}>
              Next 1-3 hours
            </div>
            <TrajectoryArrow direction={near_term} />
            <ReliabilityBadge horizon={1} reliabilityMap={forecast_reliability} />
          </div>

          <div style={{
            padding: 'var(--sp-3)',
            background: 'var(--slate-50)',
            borderRadius: '6px',
          }}>
            <div style={{
              fontSize: '12px',
              color: 'var(--slate-500)',
              marginBottom: '4px',
            }}>
              Next 6-12 hours
            </div>
            <TrajectoryArrow direction={medium_term} />
            <ReliabilityBadge horizon={6} reliabilityMap={forecast_reliability} />
          </div>
        </div>

        {/* Peak status */}
        {highest_forecast_horizon != null && highest_forecast_value != null && (
          <div style={{
            fontSize: '13px',
            color: 'var(--slate-600)',
            marginBottom: 'var(--sp-3)',
          }}>
            Highest forecast: {Math.round(highest_forecast_value)} ug/m3
            {' at '}{highest_forecast_horizon}h horizon
            {peak_passed ? ' (peak likely passed)' : ''}
          </div>
        )}

        {/* Recovery indication */}
        {recovery_text && (
          <div style={{
            fontSize: '13px',
            color: recovery_expected ? '#166534' : 'var(--slate-600)',
            background: recovery_expected ? '#f0fdf4' : 'var(--slate-50)',
            padding: 'var(--sp-2) var(--sp-3)',
            borderRadius: '6px',
            borderLeft: `3px solid ${recovery_expected ? '#16a34a' : 'var(--slate-200)'}`,
          }}>
            {recovery_text}
          </div>
        )}

        {/* Reliability note */}
        <div style={{
          marginTop: 'var(--sp-3)',
          fontSize: '12px',
          color: 'var(--slate-400)',
          fontStyle: 'italic',
        }}>
          Reliability labels are based on historical validation metrics, not numeric scores.
        </div>
      </div>
    </div>
  );
}
